<?php

/**
 * @file
 * Contains add_to_calendar_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function add_to_calendar_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the add_to_calendar_field module.
    case 'help.page.add_to_calendar_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add to Calendar Field for Event Feed') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function add_to_calendar_field_theme() {
  return [
    'add_to_calendar_field' => [
      'variables' => ['nid'=>NULL, 'googleAddCal'=>NULL, 'yahooAddCal'=>NULL, 'icsAddCal'=>NULL, 'send_email_link'=>NULL],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function add_to_calendar_field_mail($key, &$message, $params)
{
    $options = array(
        'langcode' => $message['langcode'],
    );

    $attachments = array(
        'filecontent' => $params['ics'],
        'filename' => 'Calendar-Event.ics',
        'filemime' => 'text/calendar',
    );

    switch ($key) {
        case 'send_ics_file':
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            $message['from'] = 'youraddress@yoursite.com';
            $message['subject'] = 'Add SMA event to your calendar';
            $message['params']['attachments'][] = $attachments;
            $message['body'][] = $params['message'];
            break;

    }
}
