<?php

namespace Drupal\add_to_calendar\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class CalendarLinksType.
 */
class CalendarLinksType extends ConfigFormBase {

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'calendar_links_type';
  }

  /**
   * {@inheritdoc}
   */
  protected function getEditableConfigNames() {
    return [
      'calendar_links_type.settings',
    ];
  }


  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {

    // save settings for Content type configurations
    $config = $this->config('calendar_links_type.settings');

    $form['#tree'] = TRUE;

    $form['header_info'] = [
          '#markup' =>'<h3>Disable or enable calendar links</h3>'.
           '<p>Uncheck the check boxes below to disable the calendar link from page display.</p>',
      ];

    $form['send_email'] = [
      '#type' => 'checkbox',
      '#title' => 'Send Email',
      '#default_value' => $config->get('send_email')
     ];

    $form['google'] = [
      '#type' => 'checkbox',
      '#title' => 'Google',
      '#default_value' => $config->get('google')
    ];

    $form['yahoo'] = [
      '#type' => 'checkbox',
      '#title' => 'Yahoo',
      '#default_value' => $config->get('yahoo')
    ];

    $form['download_ics'] = [
      '#type' => 'checkbox',
      '#title' => 'Download',
      '#default_value' => $config->get('download_ics')
    ];


    return parent::buildForm($form, $form_state);

  }

  public function validateForm(array &$form, FormStateInterface $form_state)
  {
      parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {

    parent::submitForm($form, $form_state);

    // Display result.
//    foreach ($form_state->getValues() as $key => $value) {
//      drupal_set_message($key . ': ' . $value);
//    }

    // save settings for Content type configurations
    $config = $this->config('calendar_links_type.settings');

    $config->set('send_email', $form_state->getValue('send_email'));
    $config->set('google', $form_state->getValue('google'));
    $config->set('yahoo', $form_state->getValue('yahoo'));
    $config->set('download_ics', $form_state->getValue('download_ics'));
    $config->save();

  }


}
